---
- hosts: kafkarh7
  vars:  
    java_archive: jdk-8u191-linux-x64.tar.gz 
    download_url: https://download.oracle.com/otn-pub/java/jdk/8u191-b12/2787e4a523244c269598db4e85c51e0c/jdk-8u191-linux-x64.tar.gz
    path_base: /usr/local/java
    path_archive: /usr/local/java/{{ java_archive }}
    scala_archive: scala-2.12.8.tgz
    scala_url: https://downloads.lightbend.com/scala/2.12.8/scala-2.12.8.tgz 
    zookeeper_archive: zookeeper-3.4.12.tar.gz
    zookeeper_url: http://mirror.cc.columbia.edu/pub/software/apache/zookeeper/zookeeper-3.4.12/zookeeper-3.4.12.tar.gz
    kafka_archive: kafka_2.12-2.1.0.tgz
    kafka_url: https://www.apache.org/dyn/closer.cgi?path=/kafka/2.1.0/kafka_2.12-2.1.0.tgz

  become: yes
  become_method: sudo
  tasks:
    - name: install libselinux-python
      yum:
        name: libselinux-python
        state: present

    - name: make necessary dirs for install
      command: mkdir -p /usr/java

    - name: install java jdk 1.8.x
#     become: yes
#     become_method: sudo
      command: "wget -q -O {{java_archive}} -P {{ path_base }}  --no-check-certificate --no-cookies --header 'Cookie: oraclelicense=accept-securebackup-cookie' {{download_url}}"
#     command: "wget -q -O {{java_archive}} --no-check-certificate --no-cookies --header 'Cookie: oraclelicense=accept-securebackup-cookie' {{download_url}} creates={{path_base}}"

    - name: download scala 2.12.x
      command: "wget -q -O {{scala_archive}} {{scala_url}}" 

    - name: download zookeeper
      command: "wget -q -O {{zookeeper_archive}} {{zookeeper_url}}"

    - namae: download kafka
      command: "wget -q -O {{kafka_archive}} {{kafka_url}}"

    - name: move downloads
      shell: |
        "for i in /home/vagrant/*;do tar xvf $i;done"
        mv `ls -d /home/vagrant/jdk*` /usr/java
        mv `ls -d /home/vagrant/*` /opt
    
#   - name: install zookeeper
#     command:

